services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nexa_music
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - nexa_pg:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nexa_music
      JWT_SECRET: altere-esta-chave-no-uso-real
    ports:
      - "3000:3000"
volumes:
  nexa_pg:
